sudo: false
language: node_js
node_js:
- '0.12'
before_script:
- npm install
- npm install -g bower
- bower install
- gulp build
deploy:
  provider: s3
  access_key_id: AKIAJB3A5ZBRAZ2ME6MQ
  secret_access_key:
    secure: r6mWodvCN7vlcQtL106MXeMYQ6dh3HMNpg0hGgbRkDcyH9GzUUeUFRewRktVvxc1xd1bkfBXpIjGfLZlKGE/pycWWXhW7h05frKmBjo2/BTWmN7c3DZMU2rcj/Ek1A7ffZoi3+F9KDTGmahrq6qPoAvpiDoxI+NbZlpnNBCa6nr2dj/0JrUdl6X1F+Di0aBhcTaqUZfcrKd49AN+nT03Qq+OehcsXXWc0B3p6Tmi9cj/thyoZyisX69xB1GtLT/UWY+IvIHaEizrdq43V6TmnhkRAd4NEg0XCjg800nwHPh6PPvnf7Xjb/3EbD7gIuXD58lllpx6hWuxBdxQHcRy6mCRuRtCB0oN+OJStkf7gxGqYweoXvQyk3VNYo42hMhrrmOaQtELol61py+L+K6C0mi8mOG6M41W+O3+4TkMex5JGTfw5IgYtsTgN1WxuGRvdqoKgMaKtKwxfbDVMRAMnx7Itf+93Z5DLaMFKZmMz6HNqwbCoYzwJYMwb+sAx8p6VvMBUkpBShPkwCzYDZT5PoFhcJhIU7gt5dmMoHHqqZA9WDp2bnGHpdKQedwEateR1uaO5Mo6pyuLMkNPFdkbMDVFHvO8ZS0edVDsaed6OUhXaBKuRVGToQyTJKx13DsF7D36tbxV37pmm7k5WehclVHoSFAFU1IiE7/UxHy8GbQ=
  bucket: www.ambestephen.com
  skip_cleanup: true
  region: us-west-2
  acl: public_read
  on:
    repo: anbestephen/ambestephen.com
